name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        type: string

env:
  DockerImageName: todoapp
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up kind
        uses: helm/kind-action@v1
        with:
          config: cluster.yml

      - name: Build Helm dependencies
        run: |
          helm dependency build ./helm-charts/todoapp

      - name: Helm install dry-run
        run: |
          helm install todoapp ./helm-charts/todoapp \
            --dry-run \
            --debug \
            --namespace todoapp \
            --create-namespace \
            --set todoapp.image.repository=${{ env.DOCKERHUB_USERNAME }}/${{ env.DockerImageName }} \
            --set todoapp.image.tag=${{ github.sha }}

      - name: Helm upgrade --install
        run: |
          helm upgrade --install todoapp ./helm-charts/todoapp \
            --atomic \
            --wait \
            --timeout 5m \
            --namespace todoapp \
            --create-namespace \
            --set todoapp.image.repository=${{ env.DOCKERHUB_USERNAME }}/${{ env.DockerImageName }} \
            --set todoapp.image.tag=${{ github.sha }}